/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package alarmclock;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.Timer;

/**
 *
 * @author mgrantprg
 */
public class AlarmClock extends javax.swing.JFrame {

    /**
     * Creates new form AlarmClock
     */
    public AlarmClock() {
        initComponents();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alarm1ButtonGroup = new javax.swing.ButtonGroup();
        alarm1 = new javax.swing.JPanel();
        alarmAtRadioButton = new javax.swing.JRadioButton();
        alarmAtHoursLabel = new javax.swing.JLabel();
        alarmAtHoursSpinner = new javax.swing.JSpinner();
        alarmAtMinsLabel = new javax.swing.JLabel();
        alarmAtMinsSpinner = new javax.swing.JSpinner();
        alarmInRadioButton = new javax.swing.JRadioButton();
        alarmInHoursLabel = new javax.swing.JLabel();
        alarmInHoursSpinner = new javax.swing.JSpinner();
        alarmInMinsLabel = new javax.swing.JLabel();
        alarmInMinsSpinner = new javax.swing.JSpinner();
        alarmActivatedCheckBox = new javax.swing.JCheckBox();
        countdownLabel = new javax.swing.JLabel();
        alarmCountdownHoursLabel = new javax.swing.JLabel();
        alarmCountdownMinsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AlarmClock");
        setName("AlarmClock");

        alarm1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alarm 1"));
        alarm1.setName("Alarm 1");

        alarm1ButtonGroup.add(alarmAtRadioButton);
        alarmAtRadioButton.setSelected(true);
        alarmAtRadioButton.setText("Alarm at");
        alarmAtRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarmAtRadioButtonActionPerformed(evt);
            }
        });

        alarmAtHoursLabel.setText("Hours");

        alarmAtHoursSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        alarmAtMinsLabel.setText("Mins");

        alarmAtMinsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        alarm1ButtonGroup.add(alarmInRadioButton);
        alarmInRadioButton.setText("Alarm in");
        alarmInRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarmInRadioButtonActionPerformed(evt);
            }
        });

        alarmInHoursLabel.setText("Hours");

        alarmInHoursSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        alarmInHoursSpinner.setEnabled(false);

        alarmInMinsLabel.setText("Mins");

        alarmInMinsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        alarmInMinsSpinner.setEnabled(false);

        alarmActivatedCheckBox.setText("Activated");
        alarmActivatedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarmActivatedCheckBoxActionPerformed(evt);
            }
        });

        countdownLabel.setText("Countdown");

        alarmCountdownHoursLabel.setText("    0");

        alarmCountdownMinsLabel.setText("    0");

        javax.swing.GroupLayout alarm1Layout = new javax.swing.GroupLayout(alarm1);
        alarm1.setLayout(alarm1Layout);
        alarm1Layout.setHorizontalGroup(
            alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alarm1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alarm1Layout.createSequentialGroup()
                            .addComponent(alarmAtRadioButton)
                            .addGap(46, 46, 46))
                        .addGroup(alarm1Layout.createSequentialGroup()
                            .addComponent(alarmAtHoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alarmAtMinsLabel)
                                .addComponent(alarmAtMinsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)))
                    .addGroup(alarm1Layout.createSequentialGroup()
                        .addComponent(alarmAtHoursLabel)
                        .addGap(102, 102, 102)))
                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alarm1Layout.createSequentialGroup()
                        .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alarmInHoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alarmInHoursLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alarmInMinsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alarmInMinsLabel))
                        .addGap(50, 50, 50)
                        .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(alarm1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(alarmCountdownHoursLabel)
                                .addGap(18, 18, 18)
                                .addComponent(alarmCountdownMinsLabel)
                                .addGap(24, 24, 24))
                            .addGroup(alarm1Layout.createSequentialGroup()
                                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countdownLabel)
                                    .addComponent(alarmActivatedCheckBox))
                                .addContainerGap())))
                    .addGroup(alarm1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(alarmInRadioButton)
                        .addContainerGap())))
        );
        alarm1Layout.setVerticalGroup(
            alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alarm1Layout.createSequentialGroup()
                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alarmAtRadioButton)
                    .addComponent(alarmInRadioButton)
                    .addComponent(alarmActivatedCheckBox))
                .addGap(7, 7, 7)
                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alarmAtHoursLabel)
                    .addComponent(alarmInHoursLabel)
                    .addComponent(alarmAtMinsLabel)
                    .addComponent(alarmInMinsLabel)
                    .addComponent(countdownLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alarmAtHoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alarmAtMinsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alarmInHoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alarmInMinsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alarmCountdownHoursLabel)
                    .addComponent(alarmCountdownMinsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alarm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alarm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alarmAtRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarmAtRadioButtonActionPerformed
        alarmAtHoursSpinner.setEnabled(true);
        alarmAtMinsSpinner.setEnabled(true);
        alarmInHoursSpinner.setEnabled(false);
        alarmInMinsSpinner.setEnabled(false);
    }//GEN-LAST:event_alarmAtRadioButtonActionPerformed

    private void alarmInRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarmInRadioButtonActionPerformed
        alarmAtHoursSpinner.setEnabled(false);
        alarmAtMinsSpinner.setEnabled(false);
        alarmInHoursSpinner.setEnabled(true);
        alarmInMinsSpinner.setEnabled(true);
    }//GEN-LAST:event_alarmInRadioButtonActionPerformed

    private void alarmActivatedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarmActivatedCheckBoxActionPerformed
        if (alarmActivatedCheckBox.isSelected()) {
            if (alarmAtRadioButton.isSelected())
                timerDelay = alarmAtDelayCalc();
            else
                timerDelay = alarmInDelayCalc();
            timerAlarm1 = new Timer(timerDelay, this.playAlarm);
            playerThread = new Thread(new PlaySoundThread("alarm-clock-1.wav", true));
            timerAlarm1.start();
        }
        else
        {
            timerAlarm1.stop();
            if (playerThread.isAlive())
                    playerThread.interrupt();
        }
    }//GEN-LAST:event_alarmActivatedCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AlarmClock().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alarm1;
    private javax.swing.ButtonGroup alarm1ButtonGroup;
    private javax.swing.JCheckBox alarmActivatedCheckBox;
    private javax.swing.JLabel alarmAtHoursLabel;
    private javax.swing.JSpinner alarmAtHoursSpinner;
    private javax.swing.JLabel alarmAtMinsLabel;
    private javax.swing.JSpinner alarmAtMinsSpinner;
    private javax.swing.JRadioButton alarmAtRadioButton;
    private javax.swing.JLabel alarmCountdownHoursLabel;
    private javax.swing.JLabel alarmCountdownMinsLabel;
    private javax.swing.JLabel alarmInHoursLabel;
    private javax.swing.JSpinner alarmInHoursSpinner;
    private javax.swing.JLabel alarmInMinsLabel;
    private javax.swing.JSpinner alarmInMinsSpinner;
    private javax.swing.JRadioButton alarmInRadioButton;
    private javax.swing.JLabel countdownLabel;
    // End of variables declaration//GEN-END:variables

    private ActionListener playAlarm = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {

            if (alarmInMinsSpinner.isEnabled())
                alarmInMinsSpinner.setEnabled(false);
            else
                alarmInMinsSpinner.setEnabled(true);

            alarmInMinsSpinner.getModel().setValue(alarmInMinsSpinner.getModel().getNextValue());

            timerAlarm1.stop();

            playerThread.start();
        }
    };

    private Timer timerAlarm1;
    private Thread playerThread;
    private Calendar currentDate;
    private int timerDelay;

    private void setTime() {
        currentDate = Calendar.getInstance();
        alarmAtHoursSpinner.getModel().setValue(currentDate.get(Calendar.HOUR_OF_DAY));
        alarmAtMinsSpinner.getModel().setValue(currentDate.get(Calendar.MINUTE));
    }

    private int alarmAtDelayCalc() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    private int alarmInDelayCalc() {
        Integer hoursInMillis = (Integer) alarmInHoursSpinner.getModel().getValue();
        Integer minsInMillis = (Integer) alarmInMinsSpinner.getModel().getValue();
        return ((hoursInMillis.intValue() * 60 * 60 *1000) + (minsInMillis.intValue() *60 * 1000));
    }
}
