/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package alarmclock;

/**
 *
 * @author mgrantprg
 */
public class AlarmClock extends javax.swing.JFrame {

    /**
     * Creates new form AlarmClock
     */
    public AlarmClock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alarm1ButtonGroup = new javax.swing.ButtonGroup();
        alarm1 = new javax.swing.JPanel();
        alarmAtHoursLabel = new javax.swing.JLabel();
        alarmInHoursLabel = new javax.swing.JLabel();
        alarmAtHoursSpinner = new javax.swing.JSpinner();
        alarmAtMinsSpinner = new javax.swing.JSpinner();
        alarmInHoursSpinner = new javax.swing.JSpinner();
        alarmInMinsSpinner = new javax.swing.JSpinner();
        alarmAtRadioButton = new javax.swing.JRadioButton();
        alarmInRadioButton = new javax.swing.JRadioButton();
        alarmAtMinsLabel = new javax.swing.JLabel();
        alarmInMinsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AlarmClock");
        setName("AlarmClock");

        alarm1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alarm 1"));
        alarm1.setName("Alarm 1");

        alarmAtHoursLabel.setText("Hours");

        alarmInHoursLabel.setText("Hours");

        alarmAtHoursSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        alarmAtMinsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        alarmInHoursSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        alarmInMinsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        alarm1ButtonGroup.add(alarmAtRadioButton);
        alarmAtRadioButton.setSelected(true);
        alarmAtRadioButton.setText("Alarm at");

        alarm1ButtonGroup.add(alarmInRadioButton);
        alarmInRadioButton.setText("Alarm in");

        alarmAtMinsLabel.setText("Mins");

        alarmInMinsLabel.setText("Mins");

        javax.swing.GroupLayout alarm1Layout = new javax.swing.GroupLayout(alarm1);
        alarm1.setLayout(alarm1Layout);
        alarm1Layout.setHorizontalGroup(
            alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alarm1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alarm1Layout.createSequentialGroup()
                            .addComponent(alarmAtRadioButton)
                            .addGap(46, 46, 46))
                        .addGroup(alarm1Layout.createSequentialGroup()
                            .addComponent(alarmAtHoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alarmAtMinsLabel)
                                .addComponent(alarmAtMinsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)))
                    .addGroup(alarm1Layout.createSequentialGroup()
                        .addComponent(alarmAtHoursLabel)
                        .addGap(102, 102, 102)))
                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alarm1Layout.createSequentialGroup()
                        .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alarmInHoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alarmInHoursLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alarmInMinsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alarmInMinsLabel)))
                    .addGroup(alarm1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(alarmInRadioButton)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        alarm1Layout.setVerticalGroup(
            alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alarm1Layout.createSequentialGroup()
                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alarmAtRadioButton)
                    .addComponent(alarmInRadioButton))
                .addGap(7, 7, 7)
                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alarmAtHoursLabel)
                    .addComponent(alarmInHoursLabel)
                    .addComponent(alarmAtMinsLabel)
                    .addComponent(alarmInMinsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alarm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alarmAtHoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alarmAtMinsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alarmInHoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alarmInMinsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alarm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alarm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AlarmClock().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alarm1;
    private javax.swing.ButtonGroup alarm1ButtonGroup;
    private javax.swing.JLabel alarmAtHoursLabel;
    private javax.swing.JSpinner alarmAtHoursSpinner;
    private javax.swing.JLabel alarmAtMinsLabel;
    private javax.swing.JSpinner alarmAtMinsSpinner;
    private javax.swing.JRadioButton alarmAtRadioButton;
    private javax.swing.JLabel alarmInHoursLabel;
    private javax.swing.JSpinner alarmInHoursSpinner;
    private javax.swing.JLabel alarmInMinsLabel;
    private javax.swing.JSpinner alarmInMinsSpinner;
    private javax.swing.JRadioButton alarmInRadioButton;
    // End of variables declaration//GEN-END:variables
}
